// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package com.randioo.compare_collections_server.protocol;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class LoginGetRoleDataRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use LoginGetRoleDataRequest.newBuilder() to construct.
    private LoginGetRoleDataRequest() {
      initFields();
    }
    private LoginGetRoleDataRequest(boolean noInit) {}
    
    private static final LoginGetRoleDataRequest defaultInstance;
    public static LoginGetRoleDataRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginGetRoleDataRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.compare_collections_server.protocol.Login.internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.compare_collections_server.protocol.Login.internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataRequest_fieldAccessorTable;
    }
    
    // optional string account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private boolean hasAccount;
    private java.lang.String account_ = "";
    public boolean hasAccount() { return hasAccount; }
    public java.lang.String getAccount() { return account_; }
    
    // optional string uuid = 2;
    public static final int UUID_FIELD_NUMBER = 2;
    private boolean hasUuid;
    private java.lang.String uuid_ = "";
    public boolean hasUuid() { return hasUuid; }
    public java.lang.String getUuid() { return uuid_; }
    
    // optional string headImageUrl = 3;
    public static final int HEADIMAGEURL_FIELD_NUMBER = 3;
    private boolean hasHeadImageUrl;
    private java.lang.String headImageUrl_ = "";
    public boolean hasHeadImageUrl() { return hasHeadImageUrl; }
    public java.lang.String getHeadImageUrl() { return headImageUrl_; }
    
    // optional string nickname = 4;
    public static final int NICKNAME_FIELD_NUMBER = 4;
    private boolean hasNickname;
    private java.lang.String nickname_ = "";
    public boolean hasNickname() { return hasNickname; }
    public java.lang.String getNickname() { return nickname_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAccount()) {
        output.writeString(1, getAccount());
      }
      if (hasUuid()) {
        output.writeString(2, getUuid());
      }
      if (hasHeadImageUrl()) {
        output.writeString(3, getHeadImageUrl());
      }
      if (hasNickname()) {
        output.writeString(4, getNickname());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAccount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAccount());
      }
      if (hasUuid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getUuid());
      }
      if (hasHeadImageUrl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getHeadImageUrl());
      }
      if (hasNickname()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getNickname());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest result;
      
      // Construct using com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest();
        return builder;
      }
      
      protected com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest.getDescriptor();
      }
      
      public com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest getDefaultInstanceForType() {
        return com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest) {
          return mergeFrom((com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest other) {
        if (other == com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        if (other.hasHeadImageUrl()) {
          setHeadImageUrl(other.getHeadImageUrl());
        }
        if (other.hasNickname()) {
          setNickname(other.getNickname());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setAccount(input.readString());
              break;
            }
            case 18: {
              setUuid(input.readString());
              break;
            }
            case 26: {
              setHeadImageUrl(input.readString());
              break;
            }
            case 34: {
              setNickname(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string account = 1;
      public boolean hasAccount() {
        return result.hasAccount();
      }
      public java.lang.String getAccount() {
        return result.getAccount();
      }
      public Builder setAccount(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAccount = true;
        result.account_ = value;
        return this;
      }
      public Builder clearAccount() {
        result.hasAccount = false;
        result.account_ = getDefaultInstance().getAccount();
        return this;
      }
      
      // optional string uuid = 2;
      public boolean hasUuid() {
        return result.hasUuid();
      }
      public java.lang.String getUuid() {
        return result.getUuid();
      }
      public Builder setUuid(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUuid = true;
        result.uuid_ = value;
        return this;
      }
      public Builder clearUuid() {
        result.hasUuid = false;
        result.uuid_ = getDefaultInstance().getUuid();
        return this;
      }
      
      // optional string headImageUrl = 3;
      public boolean hasHeadImageUrl() {
        return result.hasHeadImageUrl();
      }
      public java.lang.String getHeadImageUrl() {
        return result.getHeadImageUrl();
      }
      public Builder setHeadImageUrl(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasHeadImageUrl = true;
        result.headImageUrl_ = value;
        return this;
      }
      public Builder clearHeadImageUrl() {
        result.hasHeadImageUrl = false;
        result.headImageUrl_ = getDefaultInstance().getHeadImageUrl();
        return this;
      }
      
      // optional string nickname = 4;
      public boolean hasNickname() {
        return result.hasNickname();
      }
      public java.lang.String getNickname() {
        return result.getNickname();
      }
      public Builder setNickname(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNickname = true;
        result.nickname_ = value;
        return this;
      }
      public Builder clearNickname() {
        result.hasNickname = false;
        result.nickname_ = getDefaultInstance().getNickname();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.compare_collections_server.protocol.LoginGetRoleDataRequest)
    }
    
    static {
      defaultInstance = new LoginGetRoleDataRequest(true);
      com.randioo.compare_collections_server.protocol.Login.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.compare_collections_server.protocol.LoginGetRoleDataRequest)
  }
  
  public static final class LoginGetRoleDataResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use LoginGetRoleDataResponse.newBuilder() to construct.
    private LoginGetRoleDataResponse() {
      initFields();
    }
    private LoginGetRoleDataResponse(boolean noInit) {}
    
    private static final LoginGetRoleDataResponse defaultInstance;
    public static LoginGetRoleDataResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginGetRoleDataResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.compare_collections_server.protocol.Login.internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.compare_collections_server.protocol.Login.internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional .com.randioo.compare_collections_server.protocol.RoleData roleData = 2;
    public static final int ROLEDATA_FIELD_NUMBER = 2;
    private boolean hasRoleData;
    private com.randioo.compare_collections_server.protocol.Entity.RoleData roleData_;
    public boolean hasRoleData() { return hasRoleData; }
    public com.randioo.compare_collections_server.protocol.Entity.RoleData getRoleData() { return roleData_; }
    
    private void initFields() {
      roleData_ = com.randioo.compare_collections_server.protocol.Entity.RoleData.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasRoleData()) {
        output.writeMessage(2, getRoleData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasRoleData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRoleData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse result;
      
      // Construct using com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse();
        return builder;
      }
      
      protected com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse.getDescriptor();
      }
      
      public com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse getDefaultInstanceForType() {
        return com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse) {
          return mergeFrom((com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse other) {
        if (other == com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasRoleData()) {
          mergeRoleData(other.getRoleData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 18: {
              com.randioo.compare_collections_server.protocol.Entity.RoleData.Builder subBuilder = com.randioo.compare_collections_server.protocol.Entity.RoleData.newBuilder();
              if (hasRoleData()) {
                subBuilder.mergeFrom(getRoleData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRoleData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // optional .com.randioo.compare_collections_server.protocol.RoleData roleData = 2;
      public boolean hasRoleData() {
        return result.hasRoleData();
      }
      public com.randioo.compare_collections_server.protocol.Entity.RoleData getRoleData() {
        return result.getRoleData();
      }
      public Builder setRoleData(com.randioo.compare_collections_server.protocol.Entity.RoleData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRoleData = true;
        result.roleData_ = value;
        return this;
      }
      public Builder setRoleData(com.randioo.compare_collections_server.protocol.Entity.RoleData.Builder builderForValue) {
        result.hasRoleData = true;
        result.roleData_ = builderForValue.build();
        return this;
      }
      public Builder mergeRoleData(com.randioo.compare_collections_server.protocol.Entity.RoleData value) {
        if (result.hasRoleData() &&
            result.roleData_ != com.randioo.compare_collections_server.protocol.Entity.RoleData.getDefaultInstance()) {
          result.roleData_ =
            com.randioo.compare_collections_server.protocol.Entity.RoleData.newBuilder(result.roleData_).mergeFrom(value).buildPartial();
        } else {
          result.roleData_ = value;
        }
        result.hasRoleData = true;
        return this;
      }
      public Builder clearRoleData() {
        result.hasRoleData = false;
        result.roleData_ = com.randioo.compare_collections_server.protocol.Entity.RoleData.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.compare_collections_server.protocol.LoginGetRoleDataResponse)
    }
    
    static {
      defaultInstance = new LoginGetRoleDataResponse(true);
      com.randioo.compare_collections_server.protocol.Login.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.compare_collections_server.protocol.LoginGetRoleDataResponse)
  }
  
  public static final class SCLoginOtherSide extends
      com.google.protobuf.GeneratedMessage {
    // Use SCLoginOtherSide.newBuilder() to construct.
    private SCLoginOtherSide() {
      initFields();
    }
    private SCLoginOtherSide(boolean noInit) {}
    
    private static final SCLoginOtherSide defaultInstance;
    public static SCLoginOtherSide getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCLoginOtherSide getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.compare_collections_server.protocol.Login.internal_static_com_randioo_compare_collections_server_protocol_SCLoginOtherSide_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.compare_collections_server.protocol.Login.internal_static_com_randioo_compare_collections_server_protocol_SCLoginOtherSide_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide result;
      
      // Construct using com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide();
        return builder;
      }
      
      protected com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide.getDescriptor();
      }
      
      public com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide getDefaultInstanceForType() {
        return com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide) {
          return mergeFrom((com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide other) {
        if (other == com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.compare_collections_server.protocol.SCLoginOtherSide)
    }
    
    static {
      defaultInstance = new SCLoginOtherSide(true);
      com.randioo.compare_collections_server.protocol.Login.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.compare_collections_server.protocol.SCLoginOtherSide)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_compare_collections_server_protocol_SCLoginOtherSide_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_compare_collections_server_protocol_SCLoginOtherSide_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Login.proto\022/com.randioo.compare_colle" +
      "ctions_server.protocol\032\014Entity.proto\"`\n\027" +
      "LoginGetRoleDataRequest\022\017\n\007account\030\001 \001(\t" +
      "\022\014\n\004uuid\030\002 \001(\t\022\024\n\014headImageUrl\030\003 \001(\t\022\020\n\010" +
      "nickname\030\004 \001(\t\"}\n\030LoginGetRoleDataRespon" +
      "se\022\024\n\terrorCode\030\001 \001(\005:\0011\022K\n\010roleData\030\002 \001" +
      "(\01329.com.randioo.compare_collections_ser" +
      "ver.protocol.RoleData\"\022\n\020SCLoginOtherSid" +
      "e"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataRequest_descriptor,
              new java.lang.String[] { "Account", "Uuid", "HeadImageUrl", "Nickname", },
              com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest.class,
              com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataRequest.Builder.class);
          internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_compare_collections_server_protocol_LoginGetRoleDataResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "RoleData", },
              com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse.class,
              com.randioo.compare_collections_server.protocol.Login.LoginGetRoleDataResponse.Builder.class);
          internal_static_com_randioo_compare_collections_server_protocol_SCLoginOtherSide_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_compare_collections_server_protocol_SCLoginOtherSide_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_compare_collections_server_protocol_SCLoginOtherSide_descriptor,
              new java.lang.String[] { },
              com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide.class,
              com.randioo.compare_collections_server.protocol.Login.SCLoginOtherSide.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.compare_collections_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
